### ISSUE TITLE
Need a better way to parse command line args.

### ISSUE THREAD

**Issue by WillNilges** [WillNilges/ShelfLife#3]
@nicholastmosher Suggests https://clap.rs (https://docs.rs/clap/2.33.0/clap). This needs to be implemented because the current way of doing things is not gonna work in the future.

**Comment by nicholastmosher** [comment]
One suggestion I'd like to make on this note is to try to move all of your user-interacting code to the binary half of your crate. In this particular case, since your user interface is a CLI, that means that all of your argument parsing, stdin-reading, and stdout-printing should be moved to your binary. The library half should be left strictly with data structures and functions that communicate using those data structures. For example, in `query_known_namespace`, you have a call to `std::io::stdin()`. Since this is in the library half, you should try to extract this call out of the function, and instead pass in whatever string it was as an argument to the function. Also (and this will be trickier), you should try to move all of your print statements out of the library and into the binary. This will probably mean you'll need to break you functions up into smaller functions. In the binary, you'll call smaller functions more frequently and print between the calls to tell the user what's going on.
